name: Python - Lint

on:
  push

jobs:
  python_lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Run black
        uses: psf/black@stable

      - name: Install dev dependencies
        run: pip install -r requirements-dev.txt

      - name: Run flake8
        run: flake8 .

      - name: Run black check
        run: black --check .