name: Python - Types

on:
  push:

jobs:
  python_types:
    name: MyPy Type Check
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python_version: [ '3.10', '3.11', '3.12' ]
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python_version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python_version }}

      - name: Cache pip
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-mypy-${{ matrix.python_version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .
          pip install -r requirements.txt
          pip install -r requirements-dev.txt

      - name: Run MyPy
        run: mypy . --config-file mypy.ini # Run MyPy check on the entire project