name: Python - Test

on:
  push:

jobs:
  python_test:
    name: Test on Python ${{ matrix.python_version }} and Django ${{ matrix.django_version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        django_version: [ '3.1', '3.2', '4.0', '4.1', '4.2', '5.0' ]
        python_version: [ '3.10', '3.11', '3.12', ]
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python_version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python_version }}

    - name: Cache pip
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ matrix.python_version }}-${{ matrix.django_version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .
        pip install -U Django==${{ matrix.django_version }}
        pip install -r requirements.txt
        pip install -r requirements-dev.txt

    - name: Run tests
      run: python -m coverage run runtests.py

    - name: Generate coverage report
      run: python -m coverage xml

    - name: Upload to CodeCov
      uses: codecov/codecov-action@v2
      with:
        fail_ci_if_error: false
        token: ${{ secrets.CODECOV_TOKEN }}